services:
  - type: web
    name: kasirbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn kasirbot.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kasirbot-db
          property: connectionString
